Us 03 03
lamartm/Alinea pull request #9
Opened 2024-03-18 13:42 UTC by lamartm

2024-03-18 13:59 UTC, MorrisRoozen requested changes

2024-03-18 13:59 UTC, MorrisRoozen commented on Homepage/script.js
Name should be more specific than script.js

2024-03-18 13:59 UTC, MorrisRoozen commented on styles.css
> +/* Recommendation Slider */
If this styling is only used in the homepage, move to something like homepage.css

2024-03-18 14:31 UTC, Tatjanae reviewed
Only thing that you might (want) to change is to make a separate file for the Javascript and CSS for your carousel and put it in a separate folder (so slick.css and slick.js).

2024-03-18 14:38 UTC, MorrisRoozen commented on Homepage/homepage.html
> +<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
If these scripts can be at the top of the file, like in the head, they should be

2024-03-18 15:03 UTC, MorrisRoozen commented on Homepage/homepage.html
> +            <p  class="recommendation-description">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
double space between '<p' and 'class' 
We should probably look into getting a linter

2024-03-19 10:38 UTC, MorrisRoozen approved these changes

2024-03-19 10:40 UTC, Tatjanae approved these changes

2024-03-19 10:41 UTC, merged